import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Bell,ChevronDown,ClipboardList,Headphones,LayoutDashboard,Menu,Package,Search,Settings,ShieldCheck,TicketCheck,Users,Wrench,Zap,ArrowUpRight,Plus,MoreHorizontal}from'lucide-react';
import'./styles.css';

const metrics=[['Total Customers','1,248','+12.5%',Users,'blue'],['New Orders','84','+8.2%',Package,'purple'],['Pending Quotes','26','Needs action',ClipboardList,'orange'],['Active Services','42','+5 this week',Wrench,'red'],['Revenue','₹8.42L','+18.4%',ArrowUpRight,'green'],['Technicians','18','15 available',Users,'cyan']];
const orders=[['SB-ORD-2026-001284','Vistara Retail','LED Channel Letters','₹48,200','Under Review','12 Aug, 10:42'],['SB-ORD-2026-001283','Green Leaf Cafe','Neon Sign','₹31,500','Quotation Sent','12 Aug, 09:18'],['SB-ORD-2026-001282','Orbit Fitness','3D Acrylic','₹72,800','Production','11 Aug, 17:26'],['SB-ORD-2026-001281','Maya Fashion','Glow Sign Board','₹24,600','Ready','11 Aug, 14:05']];
const services=[['SB-SRV-2026-000461','Nova Pharmacy','LED Problem','Emergency','R. Kumar','On The Way'],['SB-SRV-2026-000460','Urban Bakery','Physical Damage','High','Unassigned','Under Review'],['SB-SRV-2026-000459','Apex Dental','Maintenance','Normal','A. Singh','Work in Progress']];
const nav=[['Overview',LayoutDashboard],['Customers',Users],['Orders',Package],['Quotations',ClipboardList],['Service tickets',TicketCheck],['Technicians',Wrench],['Sign assets',ShieldCheck],['AI support',Zap],['Reports',ArrowUpRight]];

function Badge({children}){let c=children.toLowerCase().replaceAll(' ','-');return <span className={'badge '+c}>{children}</span>}
function App(){const[active,setActive]=useState('Overview');const[query,setQuery]=useState('');const[toast,setToast]=useState('');const[live,setLive]=useState(null);const shown=useMemo(()=>orders.filter(x=>x.join(' ').toLowerCase().includes(query.toLowerCase())),[query]);function notify(t){setToast(t);setTimeout(()=>setToast(''),2400)}
useEffect(()=>{let timer;async function sync(){try{let token=sessionStorage.getItem('signfix_admin_token');if(!token){const login=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'admin@signfix.in',password:'SignFix@123'})});token=(await login.json()).token;sessionStorage.setItem('signfix_admin_token',token)}const response=await fetch('/api/admin/dashboard',{headers:{Authorization:`Bearer ${token}`}});if(response.ok)setLive(await response.json())}catch{/* Dashboard retains its last available snapshot while offline. */}}sync();timer=setInterval(sync,15000);return()=>clearInterval(timer)},[]);
return <div className="shell">
 <aside><div className="brand"><div className="brandmark">S<span>F</span></div><div><b>SignFix</b><small>Operations Suite</small></div></div><div className="workspace"><small>WORKSPACE</small><b>DL SSR INFOTECH</b><ChevronDown size={15}/></div><nav>{nav.map(([n,I])=><button key={n} className={active===n?'active':''} onClick={()=>{setActive(n);notify(`${n} workspace opened`)}}><I size={19}/>{n}{n==='Service tickets'&&<i>12</i>}</button>)}</nav><div className="help"><Headphones/><b>Need help?</b><p>Talk to SignFix support.</p><button onClick={()=>notify('Support request created')}>Contact support</button></div><button className="settings"><Settings size={18}/>Settings</button></aside>
 <main><header><button className="hamb"><Menu/></button><div className="search"><Search size={18}/><input aria-label="Global search" placeholder="Search orders, customers, tickets…" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><button className="icon" onClick={()=>notify('You have 4 new notifications')}><Bell size={20}/><i/></button><div className="user"><div>AK</div><span><b>Arun Kumar</b><small>Super Admin</small></span><ChevronDown size={15}/></div></header>
 <section className="content"><div className="headline"><div><p>Wednesday, 12 August 2026</p><h1>Good morning, Arun <span>👋</span></h1><small>Here’s what’s happening across your business today.</small></div><button className="outline" onClick={()=>notify('Report downloaded')}><ArrowUpRight size={17}/> Export report</button><button className="primary" onClick={()=>notify('New order form ready')}><Plus size={18}/> Create order</button></div>
 <div className="metrics">{metrics.map(([a,b,c,I,color])=>{const value=a==='Total Customers'?live?.customers:a==='New Orders'?live?.newOrders:a==='Active Services'?live?.activeServices:a==='Technicians'?live?.technicians:null;return <article key={a}><div className={'metricicon '+color}><I size={21}/></div><button><MoreHorizontal/></button><p>{a}</p><h2>{value??b}</h2><small className={c[0]==='+'?'positive':''}>{c}</small></article>})}</div>
 <div className="grid"><article className="chart card"><div className="cardhead"><div><h3>Business overview</h3><p>Orders and service requests</p></div><select><option>Last 6 months</option></select></div><div className="legend"><span><i className="dot blue"/>Orders</span><span><i className="dot orange"/>Service requests</span></div><div className="plot"><div className="ylabels"><span>120</span><span>90</span><span>60</span><span>30</span><span>0</span></div><svg viewBox="0 0 700 210" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#356ae6" stopOpacity=".2"/><stop offset="1" stopColor="#356ae6" stopOpacity="0"/></linearGradient></defs><path className="area" d="M0 170 C90 150 100 85 190 110 S310 40 390 75 S510 120 590 35 S670 75 700 25 L700 210 L0 210Z"/><path className="line blueLine" d="M0 170 C90 150 100 85 190 110 S310 40 390 75 S510 120 590 35 S670 75 700 25"/><path className="line orangeLine" d="M0 188 C80 165 130 180 190 150 S300 128 390 145 S500 90 590 115 S660 90 700 105"/></svg><div className="months"><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span></div></div></article>
 <article className="status card"><div className="cardhead"><div><h3>Service status</h3><p>42 active requests</p></div><button><MoreHorizontal/></button></div><div className="donut"><div><b>42</b><span>Active</span></div></div><ul><li><i className="dot blue"/>Under review <b>12</b></li><li><i className="dot purple"/>Assigned <b>14</b></li><li><i className="dot orange"/>In progress <b>9</b></li><li><i className="dot green"/>Completed <b>7</b></li></ul></article></div>
 <article className="tablecard card"><div className="cardhead"><div><h3>Recent orders</h3><p>Latest customer orders requiring attention</p></div><button className="link" onClick={()=>setActive('Orders')}>View all orders →</button></div><div className="tablewrap"><table><thead><tr><th>ORDER ID</th><th>CUSTOMER</th><th>PRODUCT</th><th>ESTIMATED PRICE</th><th>STATUS</th><th>CREATED</th><th></th></tr></thead><tbody>{shown.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={v}>{i===0?<b className="orderid">{v}</b>:i===4?<Badge>{v}</Badge>:v}</td>)}<td><MoreHorizontal size={18}/></td></tr>)}</tbody></table></div></article>
 <div className="bottomgrid"><article className="card"><div className="cardhead"><div><h3>Priority service requests</h3><p>Tickets requiring immediate attention</p></div><button className="link">View all →</button></div>{services.map(s=><div className="service" key={s[0]}><div className="serviceIcon"><Wrench size={18}/></div><div><b>{s[1]}</b><small>{s[0]} · {s[2]}</small></div><Badge>{s[3]}</Badge><span>{s[4]}</span><Badge>{s[5]}</Badge></div>)}</article><article className="card ai"><div className="cardhead"><div><h3>AI sales leads</h3><p>Captured by SignFix AI Assistant</p></div><Zap className="zap"/></div><h2>18 <small>new leads this week</small></h2><div className="leadbar"><i/><i/><i/><i/><i/></div><div className="leadstats"><span><b>8</b>New</span><span><b>5</b>Qualified</span><span><b>3</b>Quotation</span><span><b>2</b>Won</span></div><button onClick={()=>notify('AI lead inbox opened')}>Review AI leads <ArrowUpRight size={16}/></button></article></div>
 </section></main>{toast&&<div className="toast">✓ {toast}</div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
